### ISSUE TITLE
bug: command 'lana.loadLogFile' not found

### ISSUE THREAD

**Issue by trv-tproy** [certinia/debug-log-analyzer#278]
### Summary

Unable to view log files in Analyzer, with a log file open in VSCode and the extension freshly installed.
Error message occurs:
`Command 'Log: Load Apex Log For Analysis' resulted in an error (command 'lana.loadLogFile' not found)Command 'Log: Load Apex Log For Analysis' resulted in an error (command 'lana.loadLogFile' not found)`

### Steps To Reproduce:

1.  Load a .log file  -> Right click and select Log: Show Apex Log Analysis 
2. OR cmd+shift+P and select Log:Load Apex Log for Analysis

ex.
![image](https://github.com/financialforcedev/debug-log-analyzer/assets/83222424/cbefd8d2-b7a2-40e6-91f8-cc142ff6a341)

### Expected result
Log analyzer interface loads with info from the log file selected.

### Actual result
Error message modal

**VS Code Version**:
Version: 1.71.2 (Universal)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:05:37.721Z (8 mos ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.5.0
Sandboxed: No

**Log Analyzer Extension Version**:
v1.6.0

**OS and version**:
OS: Darwin arm64 22.5.0

**Comment by lcotterffdc** [comment]
hi @trv-tproy 
I have tested all the various ways of running the [`Log: Show Apex Log Analysis`](https://github.com/certinia/debug-log-analyzer/blob/1.6.0/README.md#from-an-open-log-file) command in v1.6.0 and they seem to be working for me.

I think updating vscode will solve the issue for you.
I believe this is due to a change in the way that vscode handles activation events they made in [version 1.74](https://code.visualstudio.com/updates/v1_74#_implicit-activation-events-for-declared-extension-contributions) and I neglected to update the minimum supported version of vscode for the extension (I will get that sorted).

If updating vscode does not solve the problem can you do two things for me?
1. Record a quick gif of the problem and attach it here
2. Paste the content of the output panel for Lana (CMD+SHIFT+U then select Lana from the drop down)

I hope this helps but if not let me know and I will try to get back to you asap.

**Comment by trv-tproy** [comment]
Will do, just have to get temp admin rights to let that happen, so it may be a few more days.

**Comment by lcotterffdc** [comment]
I have raised #280 to resolve the minimum required version issue and I will close this bug for now.
If you do not think this adequately resolves the issue let me know and I can reopen.

And again thanks for raising this 👍🏻

**Comment by trv-tproy** [comment]
Confirming an update cycle resolved my issues.
Thanks very much!
